//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primitive.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primitive.Cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A console app which recreates images using geometric shapes.
        /// </summary>
        internal static string DescriptionApp {
            get {
                return ResourceManager.GetString("DescriptionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex code corresponding to background color.
        /// </summary>
        internal static string DescriptionBackground {
            get {
                return ResourceManager.GetString("DescriptionBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective size of images during computation.
        /// </summary>
        internal static string DescriptionComputationSize {
            get {
                return ResourceManager.GetString("DescriptionComputationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of consecutive failures before ending each iteration.
        /// </summary>
        internal static string DescriptionFailures {
            get {
                return ResourceManager.GetString("DescriptionFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to input image.
        /// </summary>
        internal static string DescriptionInputPath {
            get {
                return ResourceManager.GetString("DescriptionInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of shapes.
        /// </summary>
        internal static string DescriptionIterations {
            get {
                return ResourceManager.GetString("DescriptionIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to output image.
        /// </summary>
        internal static string DescriptionOutputPath {
            get {
                return ResourceManager.GetString("DescriptionOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of output image.
        /// </summary>
        internal static string DescriptionOutputSize {
            get {
                return ResourceManager.GetString("DescriptionOutputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of shape.
        /// </summary>
        internal static string DescriptionShape {
            get {
                return ResourceManager.GetString("DescriptionShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of shapes to trial before starting each iteration.
        /// </summary>
        internal static string DescriptionTrials {
            get {
                return ResourceManager.GetString("DescriptionTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shape.
        /// </summary>
        internal static string ErrorInvalidShape {
            get {
                return ResourceManager.GetString("ErrorInvalidShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: [blue]{0}[/].
        /// </summary>
        internal static string MessageElapsedTime {
            get {
                return ResourceManager.GetString("MessageElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding shapes:.
        /// </summary>
        internal static string MessageProgress {
            get {
                return ResourceManager.GetString("MessageProgress", resourceCulture);
            }
        }
    }
}
